package com.netsentinel.app.data.model

/**
 * Access Point fingerprint generated by FingerprintEngine.
 */
data class Fingerprint(
    val bssid: String,
    val ssid: String,
    val ouiVendor: String,       // Manufacturer signature derived from OUI
    val hashSignature: String,   // SHA-256 fingerprint hash
    val capabilityMask: Int,
    val isKnownBaseline: Boolean = true
)
