package com.netsentinel.app.data.model

import com.netsentinel.app.engine.ThreatReason
import com.netsentinel.app.engine.ThreatSeverity
import com.netsentinel.app.engine.ThreatType

/**
 * Threat representation generated by NetTrust Engine.
 */
data class Threat(
    val id: String,
    val title: String,
    val description: String,
    val threatType: ThreatType,
    val severity: ThreatSeverity,
    val threatScore: Int, // 0 - 100 Risk Score
    val reasons: List<ThreatReason>,
    val detectedTimestampMs: Long = System.currentTimeMillis()
)
